name: build test and create installer

on:
  push:
    tags-ignore:
        - v*
  workflow_call:
    inputs:
      save-installer:
          required: true
          default: false
          type: boolean
      
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - '**.cs'
  #  - '**.csproj'

env:
  DOTNET_VERSION: '5.0' # The .NET SDK version to use
  INSTALLER_DIR: "DronePublish.Installer/Output"

jobs:
  build-test-package:
    name: build-test-package-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
        - name: Get Tag name
          uses: olegtarasov/get-tag@v2.1
          id: tagName
    
        - uses: actions/checkout@v2
    
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Restore tools
          run: dotnet tool restore

        - name: Execute build.fsx
          run: dotnet fake run build.fsx

        - name: Upload installer
          if: inputs.save-installer == true
          uses: actions/upload-artifact@v2
          with:
            name: installer
            path: ${{ env.INSTALLER_DIR }}
            retention-days: 1
