name: pre-release

on:
  workflow_dispatch:
  #push:
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - '**.cs'
  #  - '**.csproj'

env:
  DOTNET_VERSION: '5.0' # The .NET SDK version to use
  TAG: latest
  INSTALLER_DIR: "DronePublish.Installer/Output"

jobs:
  build-test-package:
    uses: nykkolas/DronePublish/.github/workflows/build-test-package.yml@main
    with:
        save-installer: true
        tag: "latest"

  pre-release:
    name: pre-release-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    #- uses: actions/checkout@v2
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: ${{ env.DOTNET_VERSION }}

    #- name: Install dependencies
    #  run: dotnet restore
      
    #- name: Build
    #  run: dotnet build --configuration Release --no-restore
    
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal

    #- name: Package
    #  run: |
    #    "%programfiles(x86)%\Inno Setup 6\iscc.exe" /dTAG=${{ env.TAG }} "DronePublish.Installer/InstallScript.iss"
    #  shell: cmd

    - name: Download installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: ${{ env.INSTALLER_DIR }}

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.TAG }}
        prerelease: true
        title: "DronePublish : Development Build"
        files: ${{ env.INSTALLER_DIR }}/*
