name: pre-release

on:
  workflow_dispatch:
  #push:
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - '**.cs'
  #  - '**.csproj'

env:
  DOTNET_VERSION: '5.0'
  GIT_TAG_NAME: "latest"
  INSTALLER_DIR: "DronePublish.Installer/Output"

jobs:
  build-test-package:
    uses: Nykkolas/DronePublish/.github/workflows/build-test-package.yml@fake-refacto
    with:
        save-installer: true
        tag: "latest" # TODO : apparemment env n'est pas accessible ici... Tellement pourri Github Actions... Ou alors il y a un truc que je ne comprends pas dans les tags

  pre-release:
    name: pre-release-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    needs: build-test-package
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Download installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: ${{ env.INSTALLER_DIR }}

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GIT_TAG_NAME }}
        prerelease: true
        title: "DronePublish : Development Build"
        files: ${{ env.INSTALLER_DIR }}/*
