name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  #push:
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - '**.cs'
  #  - '**.csproj'

env:
  DOTNET_VERSION: '5.0' # The .NET SDK version to use
  INSTALLER_DIR: "DronePublish.Installer/Output"
  
jobs:
    build-test-package:
        uses: Nykkolas/DronePublish/.github/workflows/build-test-package.yml@master
        with:
            save-installer: true

    release:
        name: release-${{matrix.os}}
        needs: build-test-package
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                #os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Download installer
              uses: actions/download-artifact@v2
              with:
                name: installer
                path: ${{ env.INSTALLER_DIR }}

            - name: Get Tag name
              uses: olegtarasov/get-tag@v2.1
              id: tagName

            - name: Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                draft: true
                title: "DronePublish : ${{ env.GIT_TAG_NAME }}"
                files: ${{ env.INSTALLER_DIR }}/*
